version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis_data:/data
    env_file:
      - .env

  polkadot:
    image: ghcr.io/subrelay/chain-worker/develop:latest
    restart: always
    depends_on:
      - redis
    environment:
      QUEUE_NAME: "block"
      CHAIN_RPC: "wss://rpc.polkadot.io"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: "redis"
      QUEUE_URL: ${QUEUE_URL}
    env_file:
      - .env

  kusama:
    image: ghcr.io/subrelay/chain-worker/develop:latest
    restart: always
    depends_on:
      - redis
    environment:
      QUEUE_NAME: "block"
      CHAIN_RPC: "wss://kusama-rpc.polkadot.io"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: "redis"
    env_file:
      - .env

  westend:
    image: ghcr.io/subrelay/chain-worker/develop:latest
    restart: always
    depends_on:
      - redis
    environment:
      QUEUE_NAME: "block"
      CHAIN_RPC: "wss://westend-rpc.polkadot.io"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: "redis"
    env_file:
      - .env

volumes:
  pgdata:
  redis_data:
