version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}
    restart: always
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - redis_data:/data

  event-service:
    image: subrelay-event-service:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3001"
    restart: always
    env_file:
      - self-hosted.env
    depends_on:
      - redis
      - postgres
      - api

  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - self-hosted.env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  redis_data:
