version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - ${DB_PORT}:${DB_PORT}
    restart: always
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine
    restart: always
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis_data:/data
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - redis
      - postgres

  event-service:
    image: subrelay-event-service:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      API_BASE_URL: ${API_BASE_URL}
      ROLLBAR_ACCESS_TOKEN: ${API_ROLLBAR_ACCESS_TOKEN}
    ports:
      - "3001"
    restart: always
    depends_on:
      - api
    env_file:
      - .env

  

volumes:
  pgdata:
  redis_data:
